languageCode = "en"
title = "Home"

[languages]
   [languages.en]
      [languages.en.params]
         displayName = "EN"
         isoCode = "en"
         languageName = "English"
         rtl = false
         dateFormat = "2 January 2006"
         description = "Personal site of Kevin Rohn" 

weight = 1
#logo = "img/author.png"
copyright = "© 2024 Kevin Rohn"

[author]
   name = "Kevin Rohn"
   image = "img/author.jpg"
   headline = "Software developer"
   bio = "Software developer"
   links = [
    { github = "https://github.com/KevinRohn" },
    { email = "mailto:kevin@rohn.tech" },
    { link = "https://rohn.tech/" },
    { linkedin = "https://www.linkedin.com/in/kevin-rohn-157329187/" }
   ]

